Metrics/LineLength:
  Max: 120
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'
    - '**/*_helper.rb'

Metrics/AbcSize:
  Exclude:
    - app/helpers/state_helper.rb
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
